'use client'
import { upload } from '@vercel/blob/client'
import { ChangeEvent, useEffect, useRef, useState } from 'react'
type Track = { id:string; title:string; color:string; url:string; pathname:string }
const colors = ['#dffb73','#b8e3ff','#ffc5d7','#e7d5ff','#ffd890','#bdf4d6']
const id = () => crypto.randomUUID()
export default function Player() {
  const [tracks, setTracks] = useState<Track[]>([]), [admin, setAdmin] = useState(false), [editing, setEditing] = useState(false), [login, setLogin] = useState(false), [password, setPassword] = useState(''), [message, setMessage] = useState(''), [active, setActive] = useState<string | null>(null), [selected, setSelected] = useState<Track | null>(null)
  const audio = useRef<HTMLAudioElement | null>(null)
  const notify = (text:string) => { setMessage(text); window.setTimeout(()=>setMessage(''), 2600) }
  const refresh = async () => { const [t,a] = await Promise.all([fetch('/api/tracks',{cache:'no-store'}),fetch('/api/auth')]); setTracks(await t.json()); setAdmin((await a.json()).authenticated) }
  useEffect(() => { refresh() }, [])
  const persist = async (next:Track[]) => { setTracks(next); await fetch('/api/tracks',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(next)}) }
  const toggleEdit = () => { if (admin) setEditing(!editing); else setLogin(true) }
  const play = (track:Track) => { if (audio.current?.src === track.url && !audio.current.paused) { audio.current.pause(); return } audio.current?.pause(); const next = new Audio(track.url); audio.current = next; setActive(track.id); next.play(); next.onended = next.onpause = () => setActive(null) }
  const signIn = async (e:React.FormEvent) => { e.preventDefault(); const r=await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})}); if(!r.ok){notify('Contraseña incorrecta.');return} setAdmin(true);setEditing(true);setLogin(false);setPassword('');notify('Modo edición activado.') }
  const onUpload = async (e:ChangeEvent<HTMLInputElement>) => { const files=[...(e.target.files || [])]; for (const file of files) { const pathname=`sonora/audio/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'-')}`; const blob=await upload(pathname,file,{access:'public',handleUploadUrl:'/api/upload'}); const item={id:id(),title:file.name.replace(/\.[^/.]+$/,''),color:colors[tracks.length%colors.length],url:blob.url,pathname:blob.pathname}; const r=await fetch('/api/tracks',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(item)}); if(!r.ok){notify('La carga terminó, pero no se pudo guardar la pista.');await refresh();return} setTracks(v=>[...v,item]) } e.target.value=''; notify('Pista guardada en la nube.') }
  const remove = async (track:Track) => { if(!confirm(`¿Eliminar “${track.title}”?`)) return; const r=await fetch('/api/tracks',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:track.id})}); setTracks(await r.json()); setSelected(null); notify('Pista eliminada.') }
  const saveDetails = async (e:React.FormEvent) => { e.preventDefault(); if(!selected) return; const next=tracks.map(t=>t.id===selected.id?selected:t); await persist(next);setSelected(null);notify('Botón actualizado.') }
  const move = async (from:number, delta:number) => { const to=from+delta;if(to<0||to>=tracks.length)return;const next=[...tracks];[next[from],next[to]]=[next[to],next[from]];await persist(next) }
  return <main className="app"><header><div className="brand"><i/>sonora</div><button className="pill" onClick={toggleEdit}>{editing?'Listo':'Editar'}</button></header><section className="hero"><h1>Tu música,<br/>en tus manos.</h1><p>Una colección que vive en la nube y se escucha desde cualquier dispositivo.</p></section><section className={'list '+(editing?'editing':'')}>{tracks.map((track,index)=><article className={'track '+(active===track.id?'playing':'')} key={track.id}><button className="play" style={{background:track.color}} onClick={()=>play(track)} aria-label={'Reproducir '+track.title}>{active===track.id?'❚❚':'▶'}</button><div className="copy"><strong>{track.title}</strong><small>Pista {String(index+1).padStart(2,'0')}</small></div>{editing&&<div className="tools"><button onClick={()=>move(index,-1)} disabled={index===0} aria-label="Subir">↑</button><button onClick={()=>move(index,1)} disabled={index===tracks.length-1} aria-label="Bajar">↓</button><button onClick={()=>setSelected({...track})} aria-label="Personalizar">•••</button></div>}</article>)}</section>{!tracks.length&&<p className="empty">Todavía no hay pistas publicadas.</p>}{editing&&<label className="upload">＋ Cargar pista<input type="file" accept="audio/*" multiple onChange={onUpload}/></label>}{message&&<div className="notice">{message}</div>}{login&&<div className="modal"><form className="panel" onSubmit={signIn}><h2>Acceso de edición</h2><p>Introduce la contraseña de administrador para gestionar las pistas.</p><input autoFocus type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Contraseña" required/><div className="actions"><button type="button" onClick={()=>setLogin(false)}>Cancelar</button><button className="dark">Entrar</button></div></form></div>}{selected&&<div className="modal"><form className="panel" onSubmit={saveDetails}><h2>Personalizar botón</h2><label>Título<input value={selected.title} maxLength={70} onChange={e=>setSelected({...selected,title:e.target.value})} required/></label><label>Color<input className="color" type="color" value={selected.color} onChange={e=>setSelected({...selected,color:e.target.value})}/></label><div className="actions"><button type="button" className="danger" onClick={()=>remove(selected)}>Eliminar</button><button type="button" onClick={()=>setSelected(null)}>Cancelar</button><button className="dark">Guardar</button></div></form></div>}</main>
}
